sudo: false
language: python
python:
  - '3.6'

env:
  - TEST=build

jobs:
  include:
    - stage: deploy
      env: []
      before_install: []
      install: []
      script: 'true'
      after_success: []
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: praekelt.org
        password:
          secure: JaB5M66nzUuB+5BprKX5dvtpcv7xIQzUMq7KD1w/rhdsX9C6YIOr4cUvTPdTePBdxta+ZZdwbcSbS4JLkmYBdH2JxseCbnNsYskOTi5Jq3FFaTxml0RzYevS2rVY0+90uRZ4Rzsmg/RujxUNrNd8wS7RyzThzA2D8JSh87raC6iNT0QBDUXOtcDxl+cWHw7WbMZDxdJBJgBds7LyxXS5IQA4K3Jef90NZ8/VRxdjZ0HcR2ilc8qJEIJQfNos3liafAtsgSRCj1Jvx0OS3t7kCyPWP1Qv9gkag7h2E8NL4il2/YMZdIyPRLGXR/S7Yd8baMWlNymVtqEAEs+ZPJDcm0+97PvlPowEeEB6N1Y+B+iG+4F38mjdWBv6OQ6ErffbpdIJg1EK/4x3BQfUKP813V8WluF9Vesto7v8MvS4X5NBYXi2b8xoHGrk5QmLT+xpFrN3tMTdjSEX27vtpn6c8vg133GW5TY2vSbShxIS3Z8YBeYYB9xyRZAKb0sqhB2U7ur16ecogoeEV1bitYAcs66zuRs4SqTbTdBFrBv7bDar+h/N7tyljmswx8qkbQcCiiDx0TDUQ4x623x51wo3MeVQhU6c+g8bNpqHJKewpY1K7+WIW2UZFx4HOu/Lay1jnJRCRB4pXw1Qc2IkrZ7SC3DHBuwEriBHQXZ6v+D6cYM=
        on:
          tags: true
          all_branches: true

cache: pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
script: ./travis.sh
