sudo: false
language: python
python:
  - '3.6'

env:
  - TEST=build

jobs:
  include:
    - stage: deploy
      env: []
      before_install: []
      install: []
      script: 'true'
      after_success: []
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: __token__
        password: kGwd8+BW5AeWb368gpXYFJ+VytheTHrpFKPOglxV1HK535d5ZF1FutzqVian/OQGIriJ2ZuiJSSeIM8pq11Pg+b/ZyJi90QgilYBnNIbEyEZNlZ91oQtpN/YA1mcCw+GUMOb7eXmv2xhqFYA59Au3dqqEIUbjH4yhItwy8iZ+zjTEZGru4k9C08g+/3NXxD7ZNUI42ZpQ8CpLXqZcJqG693u8WYQIK7neu3oV6CS8py628R+UkO0hBM+R/9sJdkC/9xdfxqZ8EUHdNYwtRTu5cpkZWq5rjXI8NDH4tpK3jO9q+30Nlw/98snUZkNCBTYW3F0QqorzorH8moMRcK2YH0Eu7Ddb/tHddbCMLlKvLuMYY2z2PstfUURlY3p7W1S27smSyFZPTEUd/VlGYU6ZpszRaYQNYZNaqrFT7MhwkNflRozExZrqw8bEgQZgFRFtbfQ5wgBWgEIYIRg/doKpmfNZnfNhBxYzq16N+bnIZremMmV1sH9liaPDLH8lwGtM07FdfwI+SBxjtekktzt1IKHVODUVKUeQjYgoxssMd85s7nWZGmcEuioGnAXl8gZTPdoBPcn8+sjlVjNVUXrB7RL9bWHWHlEih1Ri2u/DJ0rjSxHKbReSnWlNp47jGg/9LGy/NzHnZVqhh4hSiB2KcQUvS5KyHS+h2vpeBz1naI=
        on:
          tags: true
          all_branches: true

cache: pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
script: ./travis.sh
