sudo: false
language: python
python:
  - '3.6'

env:
  - TEST=build

jobs:
  include:
    - stage: deploy
      env: []
      before_install: []
      install: []
      script: 'true'
      after_success: []
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: praekelt.org
        password:
          secure: "TO0KydQmvfQuhWlmJpEJCfeBUuBVJcmJJHv7iUSwUoHwXoC4UIbTWVGMF9cO8wUrP4Y5RPRX7fxUJNMVJXwKO5VHCXwlA2s24e6IT6VbQPIFLCV4KXJBIoYtOWxGJgp7OB3VckT9rtTMwhwWFJjAfXNAs8yG4w8O98XwKn8w91Q5BcL4lcSX5j6HbPREqgdO5Uj4EL0tNwIqUfeUVrj5VTSWIELq5Buk95u9LwfiXob5z1KM3VbnW6jGv0MqfZ8/fd0d2BjxAXkDoehgcU+XJR1QSEcbYACq6+eljSw3FydX82FbbseGyCeSpKnUW1bGpReEM4xNuPLMcHgzbEabgDqese3iJz+qkgyQlz1lSJvSkDf+H82qONgSYPX7oYYUO2d2fp+g2+HZn2EP323fn3QjDlIHAzhOgbMLyHi4bUorPq2rtimKkW3NgFKvNxDO99BPe72sFIEvyTQWpKYCfcMjpU0BGXgkj2m3Dkt7QkqjMMAW4fAIYM1cQYfmVVNup5N3++Ma/Q7+O40tT8akNAdTU/0lSxdJDrcoQgd60pCGfnMqdQlOnOBebCabjTpvwlMDO/MKmvzDtZRDaIOuo6O5nOQ5K2tfXQLyxK1sI2r2s3hJ/C2Y0yQ8VL4umIK2cvIN86BRgHCLdowuRWNdxGgwD6mS2PQVw5SvwTag+jQ="
        on:
          tags: true
          all_branches: true

cache: pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
script: ./travis.sh
